"""Generate and validate the searchable MkDocs bibliography index."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from quviz.docs.bibliography import (
    BibEntry,
    Bibliography,
    Person,
    keywords,
    parse_bibtex_file,
    required_field_problems,
)
from quviz.docs.locators import typeset_dashes
from quviz.docs.pins import validate_source_pins
from quviz.docs.scan import cited_keys_in_tree, orphan_keys

ROOT = Path(__file__).resolve().parents[1]
BIB_PATH = ROOT / "references.bib"
DOCS_DIR = ROOT / "docs"
OUTPUT_PATH = DOCS_DIR / "references" / "index.md"


def person_name(person: Person) -> str:
    if person.literal:
        return person.literal
    first = " ".join(person.first_names)
    last = " ".join(person.last_names)
    return ", ".join(part for part in (last, first) if part)


def format_authors(entry: BibEntry) -> str:
    if entry.authors:
        return _display_text("; ".join(person_name(person) for person in entry.authors))
    return _display_text(entry.fields.get("organization", "Unknown"))


def _display_text(value: str) -> str:
    """Convert the tiny TeX/Markdown subset present in bibliography fields.

    That subset includes BibTeX's ``--`` ranges and ``---`` dashes. URLs, DOIs
    and revisions never come through here (``format_field_value``), so an
    identifier that contains ``--`` stays byte-exact.
    """

    return typeset_dashes(value).replace(r"\&", "&").replace("|", r"\|").replace("\n", " ")


ENTRY_TYPE_LABELS = {
    "article": "Journal article",
    "book": "Book",
    "incollection": "Book chapter",
    "online": "Online resource",
    "software": "Software",
}

FIELD_LABELS = {
    "author": "Authors",
    "booktitle": "Book title",
    "commit": "Revision",
    "doi": "DOI",
    "edition": "Edition",
    "editor": "Editors",
    "isbn": "ISBN",
    "journal": "Journal",
    "keywords": "Keywords",
    "note": "Notes",
    "number": "Issue",
    "organization": "Organization",
    "pages": "Pages",
    "publisher": "Publisher",
    "url": "Source URL",
    "urldate": "Accessed",
    "version": "Version",
    "volume": "Volume",
    "year": "Year",
}

# Put publication identity first, locators next, and audit-only details last.
# Any future supported field missing from this tuple is still emitted by
# ``metadata_rows`` in sorted order, so adding metadata cannot silently make
# the generated index less complete.
FIELD_ORDER = (
    "author",
    "editor",
    "organization",
    "year",
    "journal",
    "booktitle",
    "edition",
    "volume",
    "number",
    "pages",
    "publisher",
    "isbn",
    "version",
    "commit",
    "urldate",
    "doi",
    "url",
    "note",
    "keywords",
)


def format_field_value(entry: BibEntry, field: str, value: str) -> str:
    """Format one value without dropping the underlying metadata."""

    if field == "author":
        return format_authors(entry)
    if field == "doi":
        return f"[{value}](https://doi.org/{value})"
    if field == "url":
        return f"[{value}]({value})"
    if field == "commit":
        return f"`{value}`"
    if field == "keywords":
        return ", ".join(f"`{tag.strip()}`" for tag in value.split(",") if tag.strip())
    return _display_text(value)


def metadata_rows(entry: BibEntry) -> list[tuple[str, str]]:
    """Return a stable, complete metadata table for one bibliography entry."""

    fields = set(entry.fields) - {"title"}
    ordered = [field for field in FIELD_ORDER if field in fields]
    ordered.extend(sorted(fields - set(ordered)))
    rows = [("Type", ENTRY_TYPE_LABELS[entry.entry_type])]
    rows.extend(
        (
            FIELD_LABELS.get(field, field.replace("_", " ").title()),
            format_field_value(entry, field, entry.fields[field]),
        )
        for field in ordered
    )
    return rows


def section_name(entry: BibEntry) -> str:
    tags = keywords(entry)
    if "source-audit" in tags:
        return "Audited source material"
    if "experiment" in tags or "measurement" in tags:
        return "Experiments and measurement"
    if "chemistry" in tags or "symmetry" in tags:
        return "Symmetry and chemical interpretation"
    if "software" in tags:
        return "Software and numerical infrastructure"
    if "visualization" in tags or "education" in tags:
        return "Visualization and teaching"
    return "Physics and mathematics"


def render(bibliography: Bibliography) -> str:
    grouped: dict[str, list[tuple[str, BibEntry]]] = {}
    for key, entry in bibliography.entries.items():
        grouped.setdefault(section_name(entry), []).append((key, entry))

    lines = [
        "<!-- Generated by scripts/render_reference_index.py; do not edit manually. -->",
        "# Citation index",
        "",
        "`references.bib` is the canonical machine-readable source. Documentation citations use",
        "Pandoc-like keys such as `[@stodolna2013stark]`; the MkDocs extension validates and",
        "renders them as author-year labels.",
        "",
    ]
    order = [
        "Physics and mathematics",
        "Experiments and measurement",
        "Symmetry and chemical interpretation",
        "Visualization and teaching",
        "Audited source material",
        "Software and numerical infrastructure",
    ]
    for section in order:
        entries = grouped.get(section, [])
        if not entries:
            continue
        lines.extend([f"## {section}", ""])
        for key, entry in sorted(entries, key=lambda item: item[0]):
            title = entry.fields.get("title", key)
            lines.extend(
                [
                    f'<a id="{key}"></a>',
                    f"### `{key}` — {title}",
                    "",
                    "| Metadata | Value |",
                    "| --- | --- |",
                    *(f"| **{label}** | {value} |" for label, value in metadata_rows(entry)),
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def cited_keys() -> set[str]:
    """Keys cited in documentation prose -- code blocks and comments excluded."""

    try:
        return cited_keys_in_tree(DOCS_DIR, exclude=(OUTPUT_PATH,))
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc


def write_index(path: Path, rendered: str) -> None:
    """Write the index with LF line endings regardless of platform.

    A text-mode write on Windows would turn every LF into CRLF, and the
    byte-level docs gate (``tests/test_docs_integrity.py``) rejects any CR.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)


def index_is_current(path: Path, rendered: str) -> bool:
    """Byte-for-byte comparison, so a CRLF copy of the right text is stale."""

    return path.exists() and path.read_bytes() == rendered.encode("utf-8")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    bibliography = parse_bibtex_file(BIB_PATH)
    used = cited_keys()
    missing = used - set(bibliography.entries)
    if missing:
        raise SystemExit(f"unknown documentation citation keys: {sorted(missing)}")
    orphans = orphan_keys(bibliography, used)
    if orphans:
        raise SystemExit(
            f"orphan bibliography entries (cited nowhere, tag `keywords = {{tooling}}` "
            f"if that is intended): {orphans}"
        )
    pin_problems = validate_source_pins(bibliography.entries.values())
    if pin_problems:
        details = "\n  ".join(pin_problems)
        raise SystemExit(f"source-audit pins are missing or incoherent:\n  {details}")
    field_problems = required_field_problems(bibliography)
    if field_problems:
        details = "\n  ".join(field_problems)
        raise SystemExit(f"bibliography entries have incomplete metadata:\n  {details}")

    rendered = render(bibliography)
    if args.check:
        if not index_is_current(OUTPUT_PATH, rendered):
            raise SystemExit("reference index is stale; run scripts/render_reference_index.py")
        return 0

    write_index(OUTPUT_PATH, rendered)
    print(OUTPUT_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
